#include "unity.h"
void test_ModeLogic_Init_sets_standstill(void);
void test_ModeLogic_Init_tolerates_null(void);
void test_ModeLogic_Step_tolerates_null_args(void);
void test_SwHLR06_Hybrid_external_EV_beats_internal_ICE(void);
void test_SwHLR06_Hybrid_external_StandStill_beats_internal_ICE(void);
void test_SwHLR06_ICE_external_EV_beats_internal_Hybrid(void);
void test_SwHLR06_Start_external_Regen_beats_internal_Hybrid(void);
void test_SwHLR06_Start_with_low_SOC_no_external_goes_to_internal(void);
void test_SwHLR08_ICE_reset_to_Start_beats_ICE_to_Hybrid(void);
void test_SwHLR09_Hybrid_reset_to_Start_beats_Hybrid_to_ICE(void);
void test_SwLLR09_Start_blocked_by_P_dem_not_under_PDEM_REGEN(void);
void test_SwLLR09_Start_blocked_by_speed_not_over_SPEED_REGEN(void);
void test_SwLLR09_Start_blocked_by_wEng_not_over_ENG_ON(void);
void test_SwLLR09_Start_to_RegenB_positive(void);
void test_SwLLR10_ICE_blocked_by_P_dem(void);
void test_SwLLR10_ICE_blocked_by_speed(void);
void test_SwLLR10_ICE_blocked_by_wEng(void);
void test_SwLLR10_ICE_to_RegenB_positive(void);
void test_SwLLR11_Hybrid_blocked_by_P_dem(void);
void test_SwLLR11_Hybrid_blocked_by_speed(void);
void test_SwLLR11_Hybrid_blocked_by_wEng(void);
void test_SwLLR11_Hybrid_to_RegenB_positive(void);
void test_SwLLR12_Start_EV_blocked_by_P_dem_over_HYB_OUT(void);
void test_SwLLR12_Start_EV_blocked_by_P_dem_under_STOP_LOW(void);
void test_SwLLR12_Start_EV_blocked_by_SOC_under_SOC_EV_IN(void);
void test_SwLLR12_Start_EV_blocked_by_speed_not_over_SPEED_STOP(void);
void test_SwLLR12_Start_EV_blocked_by_speed_over_SPEED_EV_MAX(void);
void test_SwLLR12_Start_EV_blocked_by_wEng(void);
void test_SwLLR12_Start_to_EV_positive(void);
void test_SwLLR13_ICE_EV_blocked_by_P_dem_over_HYB_OUT(void);
void test_SwLLR13_ICE_EV_blocked_by_P_dem_under_STOP_LOW(void);
void test_SwLLR13_ICE_EV_blocked_by_SOC_under_SOC_EV_IN(void);
void test_SwLLR13_ICE_EV_blocked_by_speed_not_over_SPEED_STOP(void);
void test_SwLLR13_ICE_EV_blocked_by_speed_over_SPEED_EV_MAX(void);
void test_SwLLR13_ICE_EV_blocked_by_wEng(void);
void test_SwLLR13_ICE_to_EV_positive(void);
void test_SwLLR14_Hybrid_EV_blocked_by_P_dem_over_HYB_OUT(void);
void test_SwLLR14_Hybrid_EV_blocked_by_P_dem_under_STOP_LOW(void);
void test_SwLLR14_Hybrid_EV_blocked_by_SOC_under_SOC_EV_IN(void);
void test_SwLLR14_Hybrid_EV_blocked_by_speed_not_over_SPEED_STOP(void);
void test_SwLLR14_Hybrid_EV_blocked_by_speed_over_SPEED_EV_MAX(void);
void test_SwLLR14_Hybrid_EV_blocked_by_wEng(void);
void test_SwLLR14_Hybrid_to_EV_positive(void);
void test_SwLLR15_Start_StandStill_blocked_by_P_dem_over_STOP_HIGH(void);
void test_SwLLR15_Start_StandStill_blocked_by_P_dem_under_STOP_LOW(void);
void test_SwLLR15_Start_StandStill_blocked_by_speed_over_SPEED_STOP(void);
void test_SwLLR15_Start_to_StandStill_positive(void);
void test_SwLLR16_ICE_StandStill_blocked_by_P_dem_over_STOP_HIGH(void);
void test_SwLLR16_ICE_StandStill_blocked_by_P_dem_under_STOP_LOW(void);
void test_SwLLR16_ICE_StandStill_blocked_by_speed_over_SPEED_STOP(void);
void test_SwLLR16_ICE_to_StandStill_positive(void);
void test_SwLLR17_Hybrid_StandStill_blocked_by_P_dem_over_STOP_HIGH(void);
void test_SwLLR17_Hybrid_StandStill_blocked_by_P_dem_under_STOP_LOW(void);
void test_SwLLR17_Hybrid_StandStill_blocked_by_speed_over_SPEED_STOP(void);
void test_SwLLR17_Hybrid_to_StandStill_positive(void);
void test_SwLLR21_ICE_Hybrid_blocked_by_P_dem_under_HYB_MID(void);
void test_SwLLR21_ICE_Hybrid_blocked_by_SOC_under_SOC_MID(void);
void test_SwLLR21_ICE_to_Hybrid_positive(void);
void test_SwLLR23_Hybrid_stays_when_both_conditions_false(void);
void test_SwLLR23_Hybrid_to_ICE_positive_low_P_dem(void);
void test_SwLLR23_Hybrid_to_ICE_positive_low_SOC(void);
void test_boundary_P_dem_equal_HYB_LOW_allows_Hybrid_to_ICE(void);
void test_boundary_P_dem_equal_HYB_MID_allows_ICE_to_Hybrid(void);
void test_boundary_P_dem_equal_PDEM_REGEN_allows_Regen(void);
void test_boundary_P_dem_equal_STOP_LOW_allows_StandStill(void);
void test_boundary_SOC_equal_SOC_EV_IN_allows_EV(void);
void test_boundary_SOC_equal_SOC_LOW_blocks_Hybrid_to_ICE_via_SOC(void);
void test_boundary_speed_equal_SPEED_EV_MAX_allows_EV(void);
void test_boundary_speed_equal_SPEED_REGEN_blocks_Regen(void);
void test_boundary_speed_equal_SPEED_STOP_allows_StandStill(void);
void test_boundary_wEng_equal_ENG_ON_blocks_Regen(void);
void test_outputs_after_transition_to_EV(void);
void test_outputs_after_transition_to_Hybrid(void);
void test_outputs_after_transition_to_ICE(void);
void test_outputs_after_transition_to_RegenB(void);
void test_outputs_after_transition_to_StandStill(void);
int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_ModeLogic_Init_sets_standstill);
    RUN_TEST(test_ModeLogic_Init_tolerates_null);
    RUN_TEST(test_ModeLogic_Step_tolerates_null_args);
    RUN_TEST(test_SwHLR06_Hybrid_external_EV_beats_internal_ICE);
    RUN_TEST(test_SwHLR06_Hybrid_external_StandStill_beats_internal_ICE);
    RUN_TEST(test_SwHLR06_ICE_external_EV_beats_internal_Hybrid);
    RUN_TEST(test_SwHLR06_Start_external_Regen_beats_internal_Hybrid);
    RUN_TEST(test_SwHLR06_Start_with_low_SOC_no_external_goes_to_internal);
    RUN_TEST(test_SwHLR08_ICE_reset_to_Start_beats_ICE_to_Hybrid);
    RUN_TEST(test_SwHLR09_Hybrid_reset_to_Start_beats_Hybrid_to_ICE);
    RUN_TEST(test_SwLLR09_Start_blocked_by_P_dem_not_under_PDEM_REGEN);
    RUN_TEST(test_SwLLR09_Start_blocked_by_speed_not_over_SPEED_REGEN);
    RUN_TEST(test_SwLLR09_Start_blocked_by_wEng_not_over_ENG_ON);
    RUN_TEST(test_SwLLR09_Start_to_RegenB_positive);
    RUN_TEST(test_SwLLR10_ICE_blocked_by_P_dem);
    RUN_TEST(test_SwLLR10_ICE_blocked_by_speed);
    RUN_TEST(test_SwLLR10_ICE_blocked_by_wEng);
    RUN_TEST(test_SwLLR10_ICE_to_RegenB_positive);
    RUN_TEST(test_SwLLR11_Hybrid_blocked_by_P_dem);
    RUN_TEST(test_SwLLR11_Hybrid_blocked_by_speed);
    RUN_TEST(test_SwLLR11_Hybrid_blocked_by_wEng);
    RUN_TEST(test_SwLLR11_Hybrid_to_RegenB_positive);
    RUN_TEST(test_SwLLR12_Start_EV_blocked_by_P_dem_over_HYB_OUT);
    RUN_TEST(test_SwLLR12_Start_EV_blocked_by_P_dem_under_STOP_LOW);
    RUN_TEST(test_SwLLR12_Start_EV_blocked_by_SOC_under_SOC_EV_IN);
    RUN_TEST(test_SwLLR12_Start_EV_blocked_by_speed_not_over_SPEED_STOP);
    RUN_TEST(test_SwLLR12_Start_EV_blocked_by_speed_over_SPEED_EV_MAX);
    RUN_TEST(test_SwLLR12_Start_EV_blocked_by_wEng);
    RUN_TEST(test_SwLLR12_Start_to_EV_positive);
    RUN_TEST(test_SwLLR13_ICE_EV_blocked_by_P_dem_over_HYB_OUT);
    RUN_TEST(test_SwLLR13_ICE_EV_blocked_by_P_dem_under_STOP_LOW);
    RUN_TEST(test_SwLLR13_ICE_EV_blocked_by_SOC_under_SOC_EV_IN);
    RUN_TEST(test_SwLLR13_ICE_EV_blocked_by_speed_not_over_SPEED_STOP);
    RUN_TEST(test_SwLLR13_ICE_EV_blocked_by_speed_over_SPEED_EV_MAX);
    RUN_TEST(test_SwLLR13_ICE_EV_blocked_by_wEng);
    RUN_TEST(test_SwLLR13_ICE_to_EV_positive);
    RUN_TEST(test_SwLLR14_Hybrid_EV_blocked_by_P_dem_over_HYB_OUT);
    RUN_TEST(test_SwLLR14_Hybrid_EV_blocked_by_P_dem_under_STOP_LOW);
    RUN_TEST(test_SwLLR14_Hybrid_EV_blocked_by_SOC_under_SOC_EV_IN);
    RUN_TEST(test_SwLLR14_Hybrid_EV_blocked_by_speed_not_over_SPEED_STOP);
    RUN_TEST(test_SwLLR14_Hybrid_EV_blocked_by_speed_over_SPEED_EV_MAX);
    RUN_TEST(test_SwLLR14_Hybrid_EV_blocked_by_wEng);
    RUN_TEST(test_SwLLR14_Hybrid_to_EV_positive);
    RUN_TEST(test_SwLLR15_Start_StandStill_blocked_by_P_dem_over_STOP_HIGH);
    RUN_TEST(test_SwLLR15_Start_StandStill_blocked_by_P_dem_under_STOP_LOW);
    RUN_TEST(test_SwLLR15_Start_StandStill_blocked_by_speed_over_SPEED_STOP);
    RUN_TEST(test_SwLLR15_Start_to_StandStill_positive);
    RUN_TEST(test_SwLLR16_ICE_StandStill_blocked_by_P_dem_over_STOP_HIGH);
    RUN_TEST(test_SwLLR16_ICE_StandStill_blocked_by_P_dem_under_STOP_LOW);
    RUN_TEST(test_SwLLR16_ICE_StandStill_blocked_by_speed_over_SPEED_STOP);
    RUN_TEST(test_SwLLR16_ICE_to_StandStill_positive);
    RUN_TEST(test_SwLLR17_Hybrid_StandStill_blocked_by_P_dem_over_STOP_HIGH);
    RUN_TEST(test_SwLLR17_Hybrid_StandStill_blocked_by_P_dem_under_STOP_LOW);
    RUN_TEST(test_SwLLR17_Hybrid_StandStill_blocked_by_speed_over_SPEED_STOP);
    RUN_TEST(test_SwLLR17_Hybrid_to_StandStill_positive);
    RUN_TEST(test_SwLLR21_ICE_Hybrid_blocked_by_P_dem_under_HYB_MID);
    RUN_TEST(test_SwLLR21_ICE_Hybrid_blocked_by_SOC_under_SOC_MID);
    RUN_TEST(test_SwLLR21_ICE_to_Hybrid_positive);
    RUN_TEST(test_SwLLR23_Hybrid_stays_when_both_conditions_false);
    RUN_TEST(test_SwLLR23_Hybrid_to_ICE_positive_low_P_dem);
    RUN_TEST(test_SwLLR23_Hybrid_to_ICE_positive_low_SOC);
    RUN_TEST(test_boundary_P_dem_equal_HYB_LOW_allows_Hybrid_to_ICE);
    RUN_TEST(test_boundary_P_dem_equal_HYB_MID_allows_ICE_to_Hybrid);
    RUN_TEST(test_boundary_P_dem_equal_PDEM_REGEN_allows_Regen);
    RUN_TEST(test_boundary_P_dem_equal_STOP_LOW_allows_StandStill);
    RUN_TEST(test_boundary_SOC_equal_SOC_EV_IN_allows_EV);
    RUN_TEST(test_boundary_SOC_equal_SOC_LOW_blocks_Hybrid_to_ICE_via_SOC);
    RUN_TEST(test_boundary_speed_equal_SPEED_EV_MAX_allows_EV);
    RUN_TEST(test_boundary_speed_equal_SPEED_REGEN_blocks_Regen);
    RUN_TEST(test_boundary_speed_equal_SPEED_STOP_allows_StandStill);
    RUN_TEST(test_boundary_wEng_equal_ENG_ON_blocks_Regen);
    RUN_TEST(test_outputs_after_transition_to_EV);
    RUN_TEST(test_outputs_after_transition_to_Hybrid);
    RUN_TEST(test_outputs_after_transition_to_ICE);
    RUN_TEST(test_outputs_after_transition_to_RegenB);
    RUN_TEST(test_outputs_after_transition_to_StandStill);
    return UNITY_END();
}
